#!/bin/bash
curl -s -X GET 'https://api-cloud.bitmart.com/spot/v1/symbols' | jq -r '.data | [.symbols | tostring] | @csv' | sed 's/"//g' > bitmart_allsymbols
sed -i "s/\[//g" bitmart_allsymbols
sed -i "s/\]//g" bitmart_allsymbols
cat bitmart_allsymbols
