#!/bin/bash
set -x
curl --silent -X GET "https://api-cloud.bitmart.com/spot/v1/ticker?symbol=$1" | jq -cr '.data.tickers[] | [.symbol,.last_price,.high_24h,.low_24h,.fluctuation] | @csv' | sed 's/"//g' > $1.info 
cat $1.info | while IFS=',' read symbol price high low percdiff; 
do 
	echo "Symbol: $symbol"
	echo "Price: $price"
	echo "High: $high"
	echo "Low: $low"
	echo $percdiff | cut -c1-1 > $1.percsign
	echo $percdiff | sed "s/+//g" | sed "s/-//g" > $1.percdiff
	echo "24H% Diff: $(cat $1.percsign)$(echo `cat $1.percdiff` \* 100 | bc)"
	

done;
